name: Deploy naar Strato

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Upload via SFTP
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: "${{ secrets.FTP_SERVER }}"
          username: "${{ secrets.FTP_USERNAME }}"
          password: "${{ secrets.FTP_PASSWORD }}"
          port: 22
          uploads: |
            ./goodbyehair-booking.php => /STRATO-apps/wordpress_05/app/wp-content/plugins/goodbyehair-booking/goodbyehair-booking.php
